### ISSUE TITLE
Avoid dependency on LaCE_manager

### ISSUE THREAD

**Issue by andreufont** [igmhub/LaCE#14]
@jchavesmontero - pnd_archive.py has a dependency on LaCE_manager, to read the Gadget ini file. 

We should remove that dependency, if needed by copying that file to LaCE (under setup_simulations folder).

**Comment by jchavesmontero** [comment]
Solved in e164f74

**Comment by jchavesmontero** [comment]
Solving this issue in e164f74 (do not pay attention at the fact that I am removing a file, sorry!) and 44bb108

**Comment by jchavesmontero** [comment]
check out #18
