### ISSUE TITLE
Nyx emulator can not handle different number of emu_params

### ISSUE THREAD

**Issue by andreufont** [igmhub/LaCE#26]
I was hoping this to work:
`nyx_emu=nn_emulator.NNEmulator(training_set='Nyx23',emu_params=['Delta2_p', 'n_p','mF', 'sigT_Mpc', 'gamma'])`
but it crashes because in some internal linear algebra we are trying to multiply a matrix of size 6 and one of size 5. Probably because we have hardcoded somewhere that there should always be 6 emu_params?

Let's leave this for post-Durham (or even post-Summer), but good to document this type of issues.

**Comment by andreufont** [comment]
@lauracabayol - this was fixed, right? If so, we can close the issue

**Comment by lauracabayol** [comment]
yes!
