### ISSUE TITLE
Set sensible defaults for gp_emulator 

### ISSUE THREAD

**Issue by andreufont** [igmhub/LaCE#7]
I find constantly setting up the same options for the gp_emulator, including:
`asymmetric_kernel=True,rbf_only=True,`
and in the p1d_archive:
`drop_tau_rescalings=True,drop_temp_rescalings=True`

Setting these by default might avoid some confusion with new users

**Comment by andreufont** [comment]
@jchavesmontero, @lauracabayol - if you agree, I'll write a pull request to address this issue

**Comment by jchavesmontero** [comment]
@andreufont sounds good!

**Comment by lauracabayol** [comment]
Great!

**Comment by andreufont** [comment]
@lauracabayol - I believe you accidentally close the issue (it has happened to me many times). I will do the actual pull request with the changes and discuss them there.

**Comment by lauracabayol** [comment]
yes, sorry @andreufont

**Comment by andreufont** [comment]
This is now addressed in PR #8 , ready to be reviewed/accepted/merged

**Comment by andreufont** [comment]
Addressed in #8
